# frozen_string_literal: true

source 'https://rubygems.org'

# Install basic gems
gem 'charty', '>= 0.2.12'
gem 'matplotlib', '>= 1.2.0'
gem 'numpy', '>= 0.4.0'
gem 'pandas', '>= 0.3.8'
gem 'red_amber', '0.4.2'
gem 'red-arrow', '11.0.0'
gem 'red-datasets', '>= 0.1.4'
gem 'red-gandiva', '11.0.0'
gem 'red-parquet', '11.0.0'
gem 'unicode_plot', '>= 0.0.5'

# Additional gems
gem 'daru'
gem 'daru-view'
gem 'enumerable-statistics'
gem 'ffi-rzmq'
gem 'nmatrix'
gem 'nmatrix-lapacke'
gem 'numo-linalg'
gem 'numo-narray'
gem 'rbplotly'
gem 'red-arrow-numo-narray'
gem 'red-chainer'
gem 'red-datasets-arrow'
gem 'red-datasets-daru'
gem 'red-datasets-pandas'
gem 'red-plasma'
gem 'rumale'
