# frozen_string_literal: true

source 'https://rubygems.org'

#TODO:
# source "https://rubygems.pkg.github.com/b08x" do
#   gem "ferret"
#   gem "nmatrix"
#   gem 'nmatrix-lapacke'
#   gem 'rbplotly'
# end

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rbplotly", git: "https://github.com/b08x/rbplotly.git", branch: "development"
gem "nmatrix", git: "https://github.com/b08x/nmatrix.git", branch: "development"
gem "nmatrix-lapacke", git: "https://github.com/b08x/nmatrix.git", branch: "development"
gem "nmatrix-fftw", git: "https://github.com/b08x/nmatrix.git", branch: "development"


gem 'beckett'
gem 'cli-ui'
gem 'composable_operations'
gem 'decisiontree'
gem 'docx', '~> 0.8.0'
gem 'dotenv'
gem 'drydock'
gem 'engtagger'
gem 'fuzzy_match'
gem 'fuzzy-string-match'
gem 'fuzzy_tools'
gem 'gnuplot'
gem 'google_palm_api', '>= 0.1.3'
gem 'graphr'
gem 'hexapdf'
gem 'highline'
gem 'hugging-face', '~> 0.3.4'
gem 'jongleur'
gem 'json'
gem 'jsonl'
gem 'kramdown'
gem 'langchainrb'
gem 'lemmatizer'
gem 'llm_memory'
gem 'logging'
gem 'matplotlib', '>= 1.2.0'
gem 'nokogiri'
gem 'ohm'
gem 'ohm-contrib'
gem 'oj'
gem 'open3'
gem 'open4'
gem 'openssl'
gem 'open-uri'
gem 'optimist'
gem 'osc-ruby'
gem 'parallel'
gem 'pdf_paradise'
gem 'pdf-reader'
gem 'pgvector'
gem 'poppler'
gem 'pragmatic_segmenter'
gem 'pragmatic_tokenizer'
gem 'rake'
gem 'rdatasets'
gem 'redic'
gem 'redis'
gem 'roo', '~> 2.10.0'
gem 'rover-df'
gem 'rspec'
gem 'rubydown'
gem 'ruby-openai'
gem 'ruby-spacy'
gem 'safe_ruby'
gem 'scalpel'
gem 'standard'
gem 'tomoto'
gem 'vega'
gem 'verbal_expressions'
gem 'wikipedia-client', '~> 1.17.0'
gem 'wordnet'
gem 'wordnet-defaultdb'
