version: "3.9"

services:
  nlp-notebook:
    image: b08x/notebook-audio:latest
    build:
      context: .
      dockerfile: audio/Dockerfile
    volumes:
      - $HOME/Public:/home/jovyan/Public:ro
      - $HOME/Public/Workspace:/home/jovyan/Workspace
    env_file:
      - .env
    environment:
      PUID: 1000
      PGID: 1041
    ports:
      - 8888:8888
# volumes:
#   ruby_notebook:
#     driver: local
