version: "3.9"

services:
  nlp-notebook:
    image: b08x/notebook-audio:latest
    build:
      context: .
      dockerfile: audio/Dockerfile
    volumes:
      - $XDG_LIBRARY_DIR:/home/jovyan/Library:ro
      - $XDG_WORKSPACE_DIR:/home/jovyan/Workspace
    env_file:
      - .env
    environment:
      PUID: 1000
      PGID: 1041
    ports:
      - 8888:8888
