# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'awesome_print'
gem 'beckett'
gem 'charty', '>= 0.2.12'
gem 'composable_operations'
gem 'daru'
gem 'decisiontree'
gem 'irb', '>= 1.3.8.pre.9'
gem 'iruby', '>= 0.7.4'
gem 'matplotlib', '>= 1.2.0'
gem 'numpy', '>= 0.4.0'
gem 'pandas', '>= 0.3.8'
gem 'pycall', '>= 1.4.1'
gem 'rdatasets'
gem 'red_amber', '0.4.2'
gem 'red-arrow', '11.0.0'
gem 'red-datasets', '>= 0.1.4'
gem 'red-gandiva', '11.0.0'
gem 'red-parquet', '11.0.0'
gem 'scalpel'
gem 'unicode_plot', '>= 0.0.5'
# gem "u"
gem 'dotenv'
gem 'fuzzy_match'
gem 'fuzzy-string-match'
gem 'fuzzy_tools'
gem 'verbal_expressions'
# TODO: build from this repo: https://github.com/acavalin/ferret
# gem "ferret"
gem 'cli-ui'
gem 'daru-view'
gem 'docx', '~> 0.8.0'
gem 'drydock'
gem 'engtagger'
gem 'enumerable-statistics'
gem 'ffi-rzmq'
gem 'gnuplot'
gem 'google_palm_api', '>= 0.1.3'
gem 'highline'
gem 'hugging-face', '~> 0.3.4'
gem 'jongleur'
gem 'json'
gem 'jsonl'
gem 'kramdown'
gem 'langchainrb'
gem 'lemmatizer'
gem 'llm_memory'
gem 'logging'
gem 'mysql2'
# gem 'nmatrix'
# gem 'nmatrix-lapacke'
gem 'nokogiri'
gem 'numo-linalg'
gem 'numo-narray'
gem 'ohm'
gem 'ohm-contrib'
gem 'oj'
gem 'open3'
gem 'open4'
gem 'openssl'
gem 'open-uri'
# FIXME: Because open-weather-ruby-client >= 0.2.0, < 0.4.0 depends on faraday >= 1.0.0
# and every version of rbplotly depends on faraday ~> 0.9,
# open-weather-ruby-client >= 0.2.0, < 0.4.0 is incompatible with rbplotly >= 0.
# gem 'open-weather-ruby-client', '~> 0.3.0'
gem 'optimist'
gem 'osc-ruby'
gem 'parallel'
gem 'pdf_paradise'
gem 'pdf-reader'
gem 'pg'
gem 'pgvector'
gem 'poppler'
gem 'pragmatic_segmenter'
gem 'pragmatic_tokenizer'
gem 'pry'
gem 'pry-doc'
gem 'rake'
# gem 'rbplotly'
gem 'red-arrow-numo-narray'
gem 'redcarpet'
gem 'red-chainer'
gem 'red-datasets-arrow'
gem 'red-datasets-daru'
gem 'red-datasets-pandas'
gem 'redic'
gem 'redis'
gem 'red-plasma'
gem 'roo', '~> 2.10.0'
gem 'rover-df'
gem 'rspec'
gem 'rubydown'
gem 'ruby-openai'
gem 'ruby-spacy'
gem 'rumale'
gem 'safe_ruby'
gem 'sequel'
gem 'sqlite3'
gem 'standard'
gem 'tomoto'
gem 'tty-config'
gem 'tty-prompt'
gem 'vega'
gem 'wikipedia-client', '~> 1.17.0'
gem 'wordnet'
