# frozen_string_literal: true

source 'https://rubygems.org'

#TODO:
# source "https://rubygems.pkg.github.com/b08x" do
#   gem "ferret"
#   gem "nmatrix"
#   gem 'nmatrix-lapacke'
#   gem 'rbplotly'
# end

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rbplotly", git: "https://github.com/b08x/rbplotly.git", branch: "development"
gem "nmatrix", git: "https://github.com/b08x/nmatrix.git", branch: "development"
gem "nmatrix-lapacke", git: "https://github.com/b08x/nmatrix.git", branch: "development"
gem "nmatrix-fftw", git: "https://github.com/b08x/nmatrix.git", branch: "development"

# gem 'activerecord'
# gem 'awesome_print'
gem 'beckett'
# gem 'charty', '>= 0.2.12'
gem 'cli-ui'
gem 'composable_operations'
# gem 'daru'
# gem 'daru-view'
gem 'decisiontree'
gem 'docx', '~> 0.8.0'
gem 'dotenv'
gem 'drydock'
gem 'engtagger'
# gem 'enumerable-statistics'
# gem 'ffi-rzmq'
gem 'fuzzy-string-match'
gem 'fuzzy_match'
gem 'fuzzy_tools'
gem 'graphr'
gem 'gnuplot'
gem 'google_palm_api', '>= 0.1.3'
gem 'hexapdf'
gem 'highline'
gem 'hugging-face', '~> 0.3.4'
# gem 'irb', '>= 1.3.8.pre.9'
# gem 'iruby', '>= 0.7.4'
gem 'jongleur'
gem 'json'
gem 'jsonl'
gem 'kramdown'
gem 'langchainrb'
gem 'lemmatizer'
gem 'llm_memory'
gem 'logging'
gem 'matplotlib', '>= 1.2.0'
# gem 'mysql2'
gem 'nokogiri'
# gem 'numo-linalg'
# gem 'numo-narray'
# gem 'numpy', '>= 0.4.0'
gem 'ohm'
gem 'ohm-contrib'
gem 'oj'
gem 'open3'
gem 'open4'
gem 'open-uri'
gem 'openssl'
gem 'optimist'
gem 'osc-ruby'
# gem 'pandas', '>= 0.3.8'
gem 'parallel'
gem 'pdf-reader'
gem 'pdf_paradise'
# gem 'pg'
gem 'pgvector'
gem 'poppler'
gem 'pragmatic_segmenter'
gem 'pragmatic_tokenizer'
# gem 'pry'
# gem 'pry-doc'
# gem 'pycall', '>= 1.4.1'
gem 'rake'
gem 'rdatasets'
#gem 'red-arrow', '11.0.0'
#gem 'red-arrow-numo-narray'
#gem 'red-chainer'
#gem 'red-datasets', '>= 0.1.4'
#gem 'red-datasets-arrow'
#gem 'red-datasets-daru'
#gem 'red-datasets-pandas'
#gem 'red-gandiva', '11.0.0'
#gem 'red-parquet', '11.0.0'
#gem 'red-plasma'
#gem 'red_amber', '0.4.2'
# gem 'redcarpet'
gem 'redic'
gem 'redis'
gem 'roo', '~> 2.10.0'
gem 'rover-df'
gem 'rspec'
gem 'ruby-openai'
gem 'ruby-spacy'
gem 'rubydown'
# gem 'rumale'
gem 'safe_ruby'
gem 'scalpel'
# gem 'sequel'
# gem 'sqlite3'
gem 'standard'
gem 'tomoto'
# gem 'tty-config'
# gem 'tty-prompt'
# gem 'unicode_plot', '>= 0.0.5'
gem 'vega'
gem 'verbal_expressions'
gem 'wikipedia-client', '~> 1.17.0'
gem 'wordnet'
gem 'wordnet-defaultdb'
