# frozen_string_literal: true

source 'https://rubygems.org'

# Install basic gems
gem 'irb', '>= 1.3.8.pre.9'
gem 'iruby', '>= 0.7.4'
gem 'pycall', '>= 1.5.1'

gem 'activesupport'
gem 'awesome_print'
gem 'bcrypt_pbkdf'
gem 'bundler'
gem 'childprocess'
gem 'colorize'
gem 'coltrane'
gem 'debug'
gem 'dotenv'
gem 'drydock'
gem 'ed25519'
gem 'eventmachine'
gem 'ffi'
gem 'fractional'
gem 'geo_coord'
gem 'highline'
gem 'i18n'
gem 'json'
gem 'jsonl'
gem 'kramdown'
gem 'langchainrb'
gem 'logging'
gem 'minitest'
gem 'mocha'
gem 'multi_json'
gem 'mysql2'
gem 'net-ssh'
gem 'open3'
gem 'open4'
gem 'parallel'
gem 'pastel'
gem 'pg'
gem 'pry'
gem 'pry-doc'
gem 'pry-byebug'
gem 'psych'
gem 'rake'
gem 'rdoc'
gem 'rexml'
gem 'rouge'
gem 'ruby-lsp'
gem 'ruby-openai'
gem 'rugged'
gem 'ruport'
gem 'sequel'
gem 'sqlite3'
gem 'sync'
gem 'sys-proctable'
gem 'treetop'
gem 'tty-box'
gem 'tty-command'
gem 'tty-config'
gem 'tty-prompt'
gem 'tty-screen'
gem 'yaml'


#TODO:
# source "https://rubygems.pkg.github.com/b08x" do
#   gem "ferret"
#   gem "nmatrix"
#   gem 'nmatrix-lapacke'
#   gem 'rbplotly'
# end

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rbplotly", git: "https://github.com/b08x/rbplotly.git", branch: "development"
gem "nmatrix", git: "https://github.com/b08x/nmatrix.git", branch: "development"
gem "nmatrix-lapacke", git: "https://github.com/b08x/nmatrix.git", branch: "development"
gem "nmatrix-fftw", git: "https://github.com/b08x/nmatrix.git", branch: "development"

gem 'torch-rb', '0.14.1'
gem 'torchaudio'
gem 'matplotlib', '>= 1.2.0'
gem 'gnuplot'

gem 'mb-sound', git: 'https://github.com/mike-bourgeous/mb-sound.git'

gem 'mb-util', git: 'https://github.com/mike-bourgeous/mb-util.git'
gem 'mb-math', git: 'https://github.com/mike-bourgeous/mb-math.git'
